apiVersion: v1
kind: Service
metadata:
  name: gtoken-webhook-svc
  namespace: gtoken
  labels:
    app: gtoken-webhook
spec:
  ports:
  - port: 443
    targetPort: 8443
  selector:
    app: gtoken-webhook
